// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ApiNoticiasHiguey.Data;
using ApiNoticiasHiguey.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ApiNoticiasHiguey.Data.Configurations
{
    public partial class NoiciaConfiguration : IEntityTypeConfiguration<Noicia>
    {
        public void Configure(EntityTypeBuilder<Noicia> entity)
        {
            entity.HasIndex(e => e.Categoria, "UQ__Noicias__08015F8BCA4B16BA").IsUnique();

            entity.Property(e => e.Autor)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("autor");
            entity.Property(e => e.Contenido).HasColumnType("text");
            entity.Property(e => e.FechaPublicacion).HasColumnType("date");
            entity.Property(e => e.Titulo)
            .HasMaxLength(200)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Noicia> entity);
    }
}
