// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ApiNoticiasHiguey.Data;
using ApiNoticiasHiguey.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ApiNoticiasHiguey.Data.Configurations
{
    public partial class SolicitudPermisoConfiguration : IEntityTypeConfiguration<SolicitudPermiso>
    {
        public void Configure(EntityTypeBuilder<SolicitudPermiso> entity)
        {
            entity.HasKey(e => e.SolicitudId).HasName("PK__Solicitu__85E95DA7FD860DD6");

            entity.ToTable("SolicitudPermiso");

            entity.Property(e => e.SolicitudId).HasColumnName("SolicitudID");
            entity.Property(e => e.Comentario).HasMaxLength(255);
            entity.Property(e => e.EstadoSolicitud)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Pendiente");
            entity.Property(e => e.FechaRespuesta).HasColumnType("datetime");
            entity.Property(e => e.FechaSolicitud)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UsuarioId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("UsuarioID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SolicitudPermiso> entity);
    }
}
