// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ApiNoticiasHiguey.Data;
using ApiNoticiasHiguey.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ApiNoticiasHiguey.Data.Configurations
{
    public partial class UserCategoriumConfiguration : IEntityTypeConfiguration<UserCategorium>
    {
        public void Configure(EntityTypeBuilder<UserCategorium> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__UserCate__3214EC07C2E1A014");

            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(450);

            entity.HasOne(d => d.Categoria).WithMany(p => p.UserCategoria)
                .HasForeignKey(d => d.CategoriaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserCategoria_Categoria");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserCategorium> entity);
    }
}
