// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ApiNoticiasHiguey.Data.Configurations;
using ApiNoticiasHiguey.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace ApiNoticiasHiguey.Data;

public partial class NoticiasProyecttoContext : DbContext
{
    public NoticiasProyecttoContext(DbContextOptions<NoticiasProyecttoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Noicia> Noicias { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.NoiciaConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

public class ApplicationDbContext : IdentityDbContext<IdentityUser>
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) :
        base(options)
    { }
}