// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiNoticiasHiguey.Models;

public partial class Pai
{
    public int Id { get; set; }

    public string Pais { get; set; }

    public virtual ICollection<Noicia> Noicia { get; set; } = new List<Noicia>();
}